import { Fournisseur } from "../../fournisseurs/models/fournisseur.model";
import { Warehouse } from "../../warehouse/models/warehouse.model";

export type Farm = {
  id?: string;
  code?: string;
  nom?: string;
  stage?: string;
  status?: boolean;
  grouwout?: string;
  type?: string;
  cost_Center?: string;
  warehouse?: Warehouse;
  ferme_Type?: string;
  vendor?: Fournisseur;
  status_Construction?: string;
  num_Client?: string;
  manager_Code?: string;
  manager_name?: string;
  technician_Code?: string;
  technician_Name?: string;
  area_type?: string;
  owner_Name?: string;
  attachments?: string;
  address1?: string;
  address2?: string;
  customerCode?: string;
  customerName?: string;
  city_Code?: string;
  city_Name?: string;
  governorateCode?: string;
  governorateName?: string;
  zip_Code?: string;
  email?: string;
  deleted?: boolean;
  phoneNumber?: string;
  faxNumber?: string;
  farm_Area?: string;
  latitude?: number;
  longitude?: number;
};
